#!/usr/bin/perl
#
# Manage next boot actions for network booted nodes.
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# $Id$
#
# (C)opyright      Erich Focht <efocht@hpce.nec.com> (Original author)
# (C)opyright 2014 Olivier Lahaye <olivier.lahaye@cea.fr> (Qt4 fixed version)


use strict;
use utf8;
use QtCore4;
use QtGui4;

use NetBootMgr;

sub main () {
    my $app = Qt::Application(\@ARGV);
    my $window = NetBootMgr();

#    $app->setMainWidget($window);
    $window->show();
    exit $app->exec();
}

main();
