#!/usr/bin/python

###################################################################
# Copyright (c) 2007 Oak Ridge National Laboratory,
#                    Geoffroy Vallee <valleegr@ornl.gov>,
#                    All rights reserved
# Copyright (c) 2007 INRIA-IRISA,
#                    Jean Parpaillon <jean.parpaillon@inria.fr>
#                    All rights reserved
# For license information, see the COPYING file in the top level
# directory of the source
###################################################################

###################################################################
#
# Description:
#   Transform config.xml description file for OSCAR packages into
#   Debian or RPM packages.
#
# Requires:
#   python-lxml
#
###################################################################

import sys
import getopt
from Opkgc.OpkgcCompiler import *
from Opkgc.OpkgcConfig import *

def usage():
    """ Print command usage
    """
    print "Usage: " + sys.argv[0] + " [-h] [--build] [-o|--output=dir] [-i|--input=dir]--deb --rpm"
    print ""
    print "\t--build  : build packages"
    print "\t--input  : opkg directory, default current dir"
    print "\t--output : build packages in specified dir"
    print ""
    print "\tAt least, one of these option must be enabled:"
    print "\t--deb    : output Debian packaging files"
    print "\t--rpm    : output RPM packaging files"

def main():
    try:
        opts, args = getopt.getopt(sys.argv[1:], "hdrbi:o:", ["help", "deb", "rpm", "build", "input=", "output="])
    except getopt.GetoptError:
        # Print help information
        usage()
        sys.exit(2)

    # Initialize config file. Here just to detect early lack of config file
    Config()

    # Default values
    debian = False
    rpm = False
    build = False
    inputdir = "."
    output = "."
    validate = True
    
    for o, a in opts:
        if o in ("-h", "--help"):
            usage()
            sys.exit()
        if o in ("-d", "--deb"):
            debian = True
        if o in ("-r", "--rpm"):
            rpm = True
        if o in ("-b", "--build"):
            build = True
        if o in ("-i", "--input"):
            inputdir = a
        if o in ("-o", "--output"):
            output = a

    # Other options checking
    if (not debian) and (not rpm):
        usage()
        sys.exit(2)

    targets = []
    if debian:
        targets.append( CompilerDebian( inputdir, output, validate ) )
    if rpm:
        targets.append( CompilerRpm( inputdir, output, validate ) )

    for target in targets[:]:
        target.compile()
        if build:
            target.build()

if __name__ == "__main__":
    main()
