#!/usr/bin/perl
#

use strict;
use OSCAR::RepositoryManager;
use OSCAR::RepoCache;
use warnings "all";

my $rm = OSCAR::RepositoryManager->new (distro=>"ubuntu-7-i386");
if (!defined $rm) {
    die "ERROR: Impossible to create a RepositoryManager object";
}
print $rm->status();

my $repo_cache = OSCAR::RepoCache->new ();
$repo_cache->print_cache();
my $url = "http://bear.csm.ornl.gov/repos/unstable/debian-4-i386/+etch+/";
my $f = $repo_cache->get_format($url);
print "Format of the cache $url: $f\n";
$repo_cache->print_cache();

exit 0;
