PKGDEST=/tmp

deb: clean
	@echo "Debian package(s) not yet available"

rpm: clean
	@echo "RHEL package(s) obsolete use epel instead"
	# /usr/bin/build_package --type rpm --output $(PKGDEST) --url http://svn.oscar.openclustergroup.org/pkgs/downloads/heartbeat-2.0.8.tar.gz --package-name heartbeat --verbose

clean:
