#!/bin/bash

#############################################################################
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#   Copyright (c) 2014 CEA - Commissariat A l'Energie Atomique et
#                            aux EnergiesAlternatives
#                      All rights reserved.
#   Copyright (C) 2014 Olivier LAHAYE <olivier.lahaye@cea.fr>
#                      All rights reserved.
#
# $Id: $
#
#############################################################################

# Usage: $0 <nodename>
# return:
# 0: OK
# 1: WARNING (offline)
# 2: CRITICAL (down)
# 3: UNKNOWN (unknown)

RESULT=$(/opt/pbs/bin/pbsnodes -l $1)
if test $? -ne 0
then
    echo "There was a error executing: pbsnodes -l $1"
    exit 2
fi

if test -z "$RESULT"
then
    echo "$1 OK"
    exit 0
fi

if test -n "$(echo $RESULT|grep state-unknown)"
then
    echo "$1 UNKNOWN STATE"
    exit 3
fi

if test -n "$(echo $RESULT|grep down)"
then
    echo "$1 DOWN"
    exit 2
fi

if test -n "$(echo $RESULT|grep offline)"
then
    echo "$1 OFFLINE"
    exit 1
fi
