#!/usr/bin/env python
# coding=utf8

#
# oreposd: manage OSCAR repositories, fetching packages in incoming queue,
# launching package build and updating repositories
#
# Configuration is done through oreposd.conf file
#
# Copyright (C) 2007 INRIA-IRISA
#                    Jean Parpaillon <jean.parpaillon@irisa.fr>
#

import os, sys, getopt
import string, re
import signal
import logging

from Oreposd.Config import *
from Oreposd.Logger import *
from Oreposd.Incoming import *

VERSION = '0.1'

USAGE = """Usage: oreposd [ -h ] [ -v ] [ -d ] [ -k ] [ -l ]
       -h|--help      print this and exit
       -v|--version   print version and exit
       -d|--debug     add verbosity
       -k|--kill      kill an running oreposd process
       -b|--batch     don't daemonize
       -l|--log       set log file
"""

stderrLogger = None
fileLogger = None

threads = []

def alreadyRunning():
    """ Return pid of an already running process of oreposd, if any.
    """
    try:
        fd = open(Config().get("GENERAL", "pidfile"), 'r')
        pid = int(fd.readline().strip())
        return pid
    except IOError, e:
        return None

def savePid():
    fd = open(Config().get("GENERAL", "pidfile"), 'w')
    fd.write("%d" % os.getpid())
    fd.close()

def rmPid():
    os.unlink(Config().get("GENERAL", "pidfile"))

def stop(signum, frame):
    for t in threads:
        Logger().debug("Asking %s to stop" % t.getName())
        t.stop()
    for t in threads:
        t.join()

    Logger().info("oreposd main thread exit...")
    Logger().shutdown()
    rmPid()
    raise SystemExit(0)
        
#
# Main
#
def main():
    # Parse command line options
    try:
        (opts, args) = getopt.getopt(sys.argv[1:],
                                     'vhdkbl:',
                                     ['version', 'help', 'debug', 'kill', 'batch', 'log='])
    except getopt.error, msg:
        error(msg)
        SystemExit(1)

    killMode = False
    batchMode = False
    logLevel = logging.INFO
    logfileName = None
    for option, arg in opts:
        if option in ('-h', '--help'):
            print USAGE
            return
        elif option in ('-v', '--version'):
            print VERSION
            return
        elif option in ('-d', '--debug'):
            logLevel = logging.DEBUG
        elif option in ('-k', '--kill'):
            killMode = True
        elif option in ('-b', '--batch'):
            batchMode = True
        elif option in ('-l', '--log'):
            logfileName = arg

    stderrLogger = logging.StreamHandler(strm=sys.stderr)
    stderrLogger.setLevel(logLevel)
    stderrLogger.setFormatter(logging.Formatter(fmt="%(name)s [%(thread)d] %(levelname)s: %(message)s"))
    Logger().init(logLevel, [stderrLogger])

    try:
        Config()
    except ConfigParser.NoOptionError, e:
        Logger().error(e)
        raise SystemExit(1)
    
    if not logfileName and Config().isDefined("GENERAL", "logfile"):
        logfileName = Config().get("GENERAL", "logfile")

    if logfileName and not killMode:
        if not os.path.isabs(logfileName):
            logfileName = os.path.join(os.getcwd(), logfileName)
        fileLogger = logging.FileHandler(logfileName)
        fileLogger.setLevel(logLevel)
        fileLogger.setFormatter(logging.Formatter(fmt="%(asctime)s %(name)s [%(thread)d] %(levelname)s: %(message)s", datefmt="%b %d %H:%M:%S"))
        Logger().addHandler(fileLogger)

    pid = alreadyRunning()
    if killMode:
        if pid:
            Logger().info("Terminate oreposd (pid %d)" % pid)
            os.kill(pid, signal.SIGTERM)
            raise SystemExit(0)
        else:
            Logger().error("No oreposd process already running")
            raise SystemExit(1)
    else:
        if pid:
            Logger().error("An oreposd process is already running (%s exists)" % Config().get("GENERAL", "pidfile"))
            raise SystemExit(1)

    if not batchMode:
        Logger().debug("Daemonizing...")
        if os.fork() == 0:
            os.setsid()
            if os.fork() != 0:
                raise SystemExit(0)
        else:
            raise SystemExit(0)
        Logger().debug("Finished daemonizing (pid %s)" % (os.getpid(),))
        Logger().rmHandler(stderrLogger)
    savePid()

    incomingThread = Incoming()
    incomingThread.start()
    
    threads.append(incomingThread)

    signal.signal(signal.SIGTERM, stop)
    signal.signal(signal.SIGINT, stop)

    while True:
        signal.pause()

# Main
if __name__ == '__main__':
    main()

# vim: set expandtab shiftwidth=4 :
