all:
	gcc -Wall -I../.. -I/usr/include/libxml++-2.6 -I/usr/include/glibmm-2.4 -I/usr/lib64/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -o test_profile_data main.cpp ../../libv3m.a -lxml++-2.6 -lglibmm-2.4 -lglib-2.0 
