#!/usr/bin/perl
#

# Copyright (c) 2009 Geoffroy Vallee <valleegr at ornl dot gov>
#                    Oak Ridge National Laboratory
#                    All rights reserved.
#

use strict;
use warnings "all";

print "[YUME] Testing package installation...\n";

# If the user that execute tests is not root, we skip that test
if ($< != 0) {
    print "[INFO] The test is not run as root, we skip it\n";
    exit 0;
}

print "\t-> We try to install a non-existing package to check the return code\n";
my $cmd = "/usr/bin/yume --repo http://bear.csm.ornl.gov/repos/rhel-5-i386 install toto";

if (system ($cmd) == 0) {
    die "ERROR: it seems that yume does not check the installation ".
        "return code";
}

my $cmd2 = "/usr/bin/ptty_try $cmd";

my $rc = system ($cmd);
if ($rc == 0) {
    die "ERROR: it seems that yume does not check the installation ".
        "return code when using ptty_try";
}

$cmd = "/usr/bin/yume --repo http://bear.csm.ornl.gov/repos/rhel-5-i386 install yume";
if (system ($cmd) != 0) {
    die "ERROR: it seems that yume does not check the installation ".
        "return code";
}

print "[YUME] Package installation testing successful\n"
