#!/usr/bin/perl
#

# Copyright (c) 2009 Geoffroy Vallee <valleegr at ornl dot gov>
#                    Oak Ridge National Laboratory
#                    All rights reserved.
#

print "[YUME] Testing repository capabilities...\n";

# If the user that execute tests is not root, we skip that test
if ($< != 0) {
    print "[INFO] The test is not run as root, we skip it\n";
    exit 0;
}

my $cmd = "/usr/bin/yume --repo http://toto.com/rhel-5-i386 install toto";

if (system ($cmd) == 0) {
    die "ERROR: it seems that yume does not return code when the repo is invalid";
}

print "[YUME] Package repository capabilities successful\n"
