Document: torque
Title: Debian torque Manual
Author: <insert document author here>
Abstract: This manual describes what torque is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/torque/torque.sgml.gz

Format: postscript
Files: /usr/share/doc/torque/torque.ps.gz

Format: text
Files: /usr/share/doc/torque/torque.text.gz

Format: HTML
Index: /usr/share/doc/torque/html/index.html
Files: /usr/share/doc/torque/html/*.html

  
