%define prefix          /usr

%define _unpackaged_files_terminate_build 0

Summary: System Installer for the OSCAR cluster stack
Name: systeminstaller-oscar
Version: 2.1.2
Release: 1
License: GPL
URL: http://systeminstaller.sourceforge.net
Group: Applications/System
Source: %{name}.tar.gz

BuildArchitectures: noarch
BuildRequires: /usr/bin/perl, perl(AppConfig), systemimager-server >= 3.5.0, systemconfigurator, perl(MLDBM)
Requires: /usr/bin/perl, perl(AppConfig), systemimager-server >= 3.5.0, systemconfigurator, perl(MLDBM), packman-depman
Vendor: http://oscar.openclustergroup.org
Packager: OSCAR developer team
Prefix: %prefix
Buildroot: /var/tmp/%{name}-%{version}-root
AutoReqProv: no
Provides: systeminstaller = %{version}

%package x11
Summary: System Installer Tk Gui
Version: %version
License: GPL
URL: http://systeminstaller.sourceforge.net
Group: Applications/System
Requires: systeminstaller >= 1.00, perl-Tk
Vendor: http://oscar.openclustergroup.org
Packager: OSCAR developer team
Prefix: %prefix
Buildroot: /var/tmp/%{name}-%{version}-root
AutoReqProv: no
Provides: systeminstaller-x11 = %{version}

%description
System Installer provides a unified image building tool. 
It is intended to be distribution and architecture 
independent. It interfaces with SystemImager and 
System Configurator. This version of SystemInstaller is
adapted for use with the OSCAR cluster stack and requires
some of the OSCAR infrastructure.

%description x11
System Installer Perl Tk User Interface

%prep
%setup -n %{name}

# No configure, no make, just copy files to the output dir.
%build
mkdir -p /var/tmp/%{name}-%{version}-root/usr/share/man/man5
mkdir -p /var/tmp/%{name}-%{version}-root/usr/share/man/man1
perl Makefile.PL PREFIX=/var/tmp/%{name}-%{version}-root%{prefix} INSTALLSITELIB=/var/tmp/%{name}-%{version}-root/usr/lib/systeminstaller INSTALLMAN1DIR=/var/tmp/%{name}-%{version}-root/usr/share/man/man1 INSTALLMAN3DIR=/var/tmp/%{name}-%{version}-root/usr/share/man/man3
# fix problem with the Makefile autogenerated on RHEL4...
sed -e 's/$(POD2MAN) --section=1 --perm_rw=$(PERM_RW)/$(POD2MAN)/' \
    -e 's/$(POD2MAN) --section=3 --perm_rw=$(PERM_RW)/$(POD2MAN)/' <Makefile >Makefile.new
mv Makefile.new Makefile
make
make test
make install
rm -rf /var/tmp/%{name}-%{version}-root/usr/lib/systeminstaller/auto*
rm -f /var/tmp/%{name}-%{version}-root/var/lib/sis/*

%clean
#rm -fr $RPM_BUILD_DIR/%{name}-%{version}
rm -rf /var/tmp/%{name}-%{version}-root

%files
%defattr(-,root,root)
%doc README 
%doc CHANGELOG
%doc COPYING
%doc INSTALL
%doc samples/systeminstaller.conf
%doc samples/disktable
%{prefix}/bin/mk*
%doc /usr/share/man/man1/mk*
%doc /usr/share/man/man1/SIS*
%doc /usr/share/man/man5/systeminstaller*
%doc /usr/share/man/man3/SIS*
%doc /usr/share/man/man3/SystemInstaller::*
/usr/lib/systeminstaller/SIS
/usr/lib/systeminstaller/Util
/usr/lib/systeminstaller/SystemInstaller/*pm
/usr/lib/systeminstaller/SystemInstaller/Package
/usr/lib/systeminstaller/SystemInstaller/PackageBest
/usr/lib/systeminstaller/SystemInstaller/Image
/usr/lib/systeminstaller/SystemInstaller/Partition
%dir /usr/lib/systeminstaller
%dir /usr/lib/systeminstaller/SystemInstaller
%dir /etc/systeminstaller
%dir /var/lib/sis/
%config /etc/systeminstaller/*

%files x11
%defattr(-,root,root)
%{prefix}/bin/tksis
%dir /usr/lib/systeminstaller/SystemInstaller/Tk
%dir /usr/lib/systeminstaller/Tk
%dir /usr/share/systeminstaller/images
/usr/share/systeminstaller/images/*
%doc /usr/share/man/man1/tksis*
/usr/lib/systeminstaller/SystemInstaller/Tk/*
/usr/lib/systeminstaller/Tk/*

%post
for i in client image adapter; do
    touch /var/lib/sis/$i
done

%preun
# if last installed instance remove the sis database files
# 
if [ $1 -eq 0 ]; then
    cd /var/lib/sis
    for i in client image adapter; do
        rm -f $i $i.dir $i.pag
    done
fi


%changelog
* Sun Feb 12 2006 Erich Focht
- Removed stuff which is either obsolete or not used with OSCAR.
- Removed distinfo and need for distro detection.
- Improved progress bar code.

* Sat Feb 11 2006 Bernard Li <bli@bcgsc.ca>
- Fix tksis bug (patch by Steven A. DuChene)
- Fix for OSCAR bug #1343429 - "Use of uninitialized value in hash element"

* Fri Jan 13 2006 Erich Focht
- bug fix for better detection of nodev filesystems in disktab files

* Wed Nov 30 2005 Erich Focht <efocht@hpce.nec.com>
- generating /etc/mdadm.conf when the disktable contains RAID definitions

* Fri Jul 29 2005 Erich Focht <efocht@hpce.nec.com>
- fixed removal of sis database files on deinstallation
- added flamethrower.conf update in mksiimage
- deleted image addition to flamethrower.conf in lib/SystemInstaller/Tk/Image.pm

* Wed Jul 27 2005 Erich Focht <efocht@hpce.nec.com>
- fixed flamethrower setup for images

* Wed Jul 20 2005 Erich Focht <efocht@hpce.nec.com>
- added Mandriva and CentOS support
- added --update option to mksiimage (update arch or location)
- enabld coexistence of architectures in dhcpd (mkdhcpd_conf)
- added x64_64 to bin/buildimage

* Fri Jul 15 2005 Erich Focht <efocht@hpce.nec.com>
- repackaged for OSCAR
- moved ugly external patches (after RPM install) into RPM
- splitted up OSCAR 4.X patches into digestible pieces
- support for systemimager-3.5.X (API change)
- support for x86_64
- added forced architecture in rpmlists ($pkg:$arch)
- added support for Scientific Linux
- added support for software raid1

* Tue Dec 17 2002 Michael Chase-Salerno <mchasal@users.sf.net>

- Changes for stable prereqs.

* Wed Dec 4 2002 Michael Chase-Salerno <mchasal@users.sf.net>

- Changes for MLDBM based database.

* Thu Aug 30 2001 Sean Dague <japh@us.ibm.com>

- Initial spec file.
