PKGDEST=/tmp

deb: clean
	#/usr/bin/build_package --type deb --output $(PKGDEST) --url http://svn.oscar.openclustergroup.org/pkgs/downloads/apitest-1.0.1.tar.gz --package-name apitest --verbose

rpm: clean
	#/usr/bin/build_package --type rpm --output $(PKGDEST) --url http://svn.oscar.openclustergroup.org/pkgs/downloads/apitest-1.0.1.tar.gz --package-name apitest --verbose

clean:
