#!/usr/bin/perl
#
# (C)opyright Oak Ridge National Laboratory 
#             Geoffroy Vallee <valleegr@ornl.gov>
#             All rights reserved
#
###############################################################################
# This tool creates Deb packages for OSCAR. 
# WARNING the current script assumes OSCAR source is within a directory named
# "oscar", all other names will create a failure. In the future we may want to
# use a tarball.
# Parameter: OSCAR source path.
# Return: 0 if success.
# TODO: find a way to install the repositories (/tftpboot stuff).
###############################################################################

use strict;
use Carp;

my $source_location = shift;
my $packaging_dir = "/tmp/oscar-debian";
my $cmd;
my $verbose = 1;

if ($source_location eq "") {
    croak ("ERROR: Impossible to find OSCAR source ($source_location)\n".
    	   "build_oscar_debs must be used with a parameter that gives the ".
	   "path to the oscar source");
}

# We initialize the packaging environment
$cmd = "rm -rf " . $packaging_dir . "; mkdir -p $packaging_dir";
print "Executing: $cmd\n" if ($verbose);
if (system ($cmd)) {
    croak ("ERROR: Impossible to initialized the packaging environment");
}

# We copy sources for package creation
print ("We copy sources for package creation\n");
$cmd = "cp -r $source_location $packaging_dir; " .
    "rm -rf `find $packaging_dir -name .svn`";
print "Executing: $cmd\n" if ($verbose);
if (system ($cmd)) {
    croak ("ERROR: Impossible to copy OSCAR sources");
}

# We copy Debian files for package creation
print ("We copy Debian files for package creation\n");
$cmd = "cp -rf debian $packaging_dir/oscar";
print "Executing: $cmd\n" if ($verbose);
if (system ($cmd)) {
    croak ("ERROR: Impossible to copy Debian files for package creation");
}

# We create Debian packages
$cmd = "cd $packaging_dir/oscar; dpkg-buildpackage -rfakeroot -us -uc";
print "Executing: $cmd\n" if ($verbose);
if (system ($cmd)) {
    croak ("ERROR: Impossible to create Debian packages");
}

print "Done!\n";
print "Debian packages are available in $packaging_dir\n";

exit (0);

