#!/usr/bin/perl
#

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#   Copyright (c) 2010  Geoffroy Vallee <valleegr@ornl.gov>
#                       Oak Ridge National Laboratory
#                       All rights reserved.

BEGIN {
    if (defined $ENV{OSCAR_HOME}) {
        unshift @INC, "$ENV{OSCAR_HOME}/lib";
    }
}

use strict;
use warnings "all";
use Carp;

use OSCAR::NAT;

# We check which interface we must use for NAT
my $extif = OSCAR::NAT::get_extif ();

# We create the script to setup NAT
my $file = "/etc/init.d/setup_nat.sh";
if (OSCAR::NAT::generate_iptables_script ($file, $extif)) {
    die ("ERROR: Impossible to generate $file");
}

# We should add the service into rc2.d but OSCAR::SystemServices does not
# support it yet.
