DESTDIR=

all:

install:
	install -d $(DESTDIR)/usr/bin/
	install -d $(DESTDIR)/usr/share/man/man8/
	install -m 644 rapt.8 $(DESTDIR)/usr/share/man/man8/rapt.8
	install -m 755 rapt $(DESTDIR)/usr/bin/rapt
