#!/bin/bash
#

# Copyright (c) 2006 Oak Ridge National Laboratory,
#                    Geoffroy Vallee <valleegr@ornl.gov>
#                    All rights reserved
# This file is part of the libv3m software.  For license information,
# see the COPYING file in the top level directory of the source

# This script download the image for netboot simulation. Note this image is not 
# in SVN because we do not want to pollute SVN

DESTDIR="../bin"
NETBOOT_IMAGE_VERSION="1.9"
BASE_URL="http://bear.csm.ornl.gov/pub/downloads/v2m/netboot_image"

if [ ! -f "$DESTDIR/netboot_emulation_$NETBOOT_IMAGE_VERSION.img.bz2" ]; then
	echo "Downloading the netboot image..."
	wget $BASE_URL/netboot_emulation_$NETBOOT_IMAGE_VERSION.img.bz2
	mv ./netboot_emulation_$NETBOOT_IMAGE_VERSION.img.bz2 $DESTDIR
	echo "The image is saved in $DESTDIR"
else
	echo "The netboot image already exists"
fi